#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<EOSQL
    CREATE USER ${FLEA_MARKET_DB_USER} WITH PASSWORD '${FLEA_MARKET_DB_PASSWORD}';
    CREATE DATABASE ${FLEA_MARKET_DB} OWNER ${FLEA_MARKET_DB_USER};

    CREATE USER ${KEYCLOAK_DB_USER} WITH PASSWORD '${KEYCLOAK_DB_PASSWORD}';
    CREATE DATABASE ${KEYCLOAK_DB} OWNER ${KEYCLOAK_DB_USER};
EOSQL
