spring:
  application:
    name: flea-market

  datasource:
    url: jdbc:postgresql://localhost:5432/${FLEA_MARKET_DB:flea_market_db}
    username: ${FLEA_MARKET_DB_USER:flea_market_user}
    password: ${FLEA_MARKET_DB_PASSWORD:flea_market_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/flea-market
          jwk-set-uri: http://localhost:8081/realms/flea-market/protocol/openid-connect/certs
